### PR TITLE
Remove prerequisites

### PR DESCRIPTION
**Pull request by daxpedda**
I believe this isn't needed anymore, I confirmed it in a virtual machine.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
How do you test this? (E.g. which distribution + desktop environment does your VM have?) For an other project of mine, I set up a virtual NixOS and made a nix expression to test which dependencies are sufficient, but that's a quite cumbersome approach for me considering that nix expressions are still mostly black magic to me.

**Comment by ArturKovacs** [comment]
If you tried it on a clean installation and it worked without the dependency, then it's probably good. If you installed some devy stuff other than rust itself on these machines then I'm not sure how accurate this is.

**Comment by ArturKovacs** [comment]
I think I'm tired. If you know for sure that this pacakge wasn't isntalled (simply by checking whether it was installed) at the time of compiling, then it's perfect.

**Comment by daxpedda** [comment]
It was a fresh installation and I did check that the package wasn't installed.
I understand your tiredness :)

**Pull request merged**
